name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'enviorment to deploy'
        required: true
        default: 'staging'
        type:  choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-lateset
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }}"
