name: Welcome Action

on: [push, pull_request]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello, GitHub Actions!"

      - name: Print current date
        run: date

      - name: Print system info
        run: uname -a

      - name: envairoment variables printing
        run:  echo "the enviroment is: ${{ env.env }}"

      - name: Disk space check
        run: df -h

      - name: List files
        run: ls -la
